[build]
  command = "gem update --system && bundle config set path 'vendor/bundle' && bundle install && jekyll build"
  publish = "_site"

[context.production.environment]
  NODE_VERSION = "16.20.0" # Specify the required Node.js version
